In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/home/frankenstein/ApexPlanet_Internship/Task_1_Data_Immersion_Wrangling/data/raw/Delinquency_prediction_dataset (1).csv')

In [5]:
df.head()

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6
0,CUST0001,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,EMP,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late
1,CUST0002,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time
2,CUST0003,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late
3,CUST0004,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late
4,CUST0005,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late

In [6]:
df.shape

(500, 19)

In [7]:
df.columns

Index(['Customer_ID', 'Age', 'Income', 'Credit_Score', 'Credit_Utilization',
       'Missed_Payments', 'Delinquent_Account', 'Loan_Balance',
       'Debt_to_Income_Ratio', 'Employment_Status', 'Account_Tenure',
       'Credit_Card_Type', 'Location', 'Month_1', 'Month_2', 'Month_3',
       'Month_4', 'Month_5', 'Month_6'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           500 non-null    object
 1   Age                   500 non-null    int64
 2   Income                461 non-null    float64
 3   Credit_Score          498 non-null    float64
 4   Credit_Utilization    500 non-null    float64
 5   Missed_Payments       500 non-null    int64
 6   Delinquent_Account    500 non-null    int64
 7   Loan_Balance          471 non-null    float64
 8   Debt_to_Income_Ratio  500 non-null    float64
 9   Employment_Status     500 non-null    object
 10  Account_Tenure        500 non-null    int64
 11  Credit_Card_Type      500 non-null    object
 12  Location              500 non-null    object
 13  Month_1               500 non-null    object
 14  Month_2               500 non-null    object
 15  Month_3               500 non-null    object
 16  Month_4               500 non-null    object
 17  Month_5               500 non-null    object
 18  Month_6               500 non-null    object
dtypes: float64(5), int64(4), object(10)
memory usage: 74.3+ KB

In [9]:
df.describe()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Account_Tenure
count,500.000000,461.000000,498.000000,500.000000,500.000000,500.000000,471.000000,500.000000,500.000000
mean,46.266000,108379.893709,577.716867,0.491446,2.968000,0.160000,48654.428875,0.298862,9.740000
std,16.187629,53662.723741,168.881211,0.197103,1.946935,0.366973,29395.537273,0.094521,5.923054
min,18.000000,15404.000000,301.000000,0.050000,0.000000,0.000000,612.000000,0.100000,0.000000
25%,33.000000,62295.000000,418.250000,0.356486,1.000000,0.000000,23716.500000,0.233639,5.000000
50%,46.500000,107658.000000,586.000000,0.485636,3.000000,0.000000,45776.000000,0.301634,10.000000
75%,59.250000,155734.000000,727.250000,0.634440,5.000000,0.000000,75546.500000,0.362737,15.000000
max,74.000000,199943.000000,847.000000,1.025843,6.000000,1.000000,99620.000000,0.552956,19.000000

In [10]:
df.dtypes

Customer_ID              object
Age                       int64
Income                  float64
Credit_Score            float64
Credit_Utilization      float64
Missed_Payments           int64
Delinquent_Account        int64
Loan_Balance            float64
Debt_to_Income_Ratio    float64
Employment_Status        object
Account_Tenure            int64
Credit_Card_Type         object
Location                 object
Month_1                  object
Month_2                  object
Month_3                  object
Month_4                  object
Month_5                  object
Month_6                  object
dtype: object

In [11]:
df.isnull().sum()

Customer_ID              0
Age                      0
Income                  39
Credit_Score             2
Credit_Utilization       0
Missed_Payments          0
Delinquent_Account       0
Loan_Balance            29
Debt_to_Income_Ratio     0
Employment_Status        0
Account_Tenure           0
Credit_Card_Type         0
Location                 0
Month_1                  0
Month_2                  0
Month_3                  0
Month_4                  0
Month_5                  0
Month_6                  0
dtype: int64

In [12]:
(df.isnull().sum() / len(df)) * 100

Customer_ID             0.0
Age                     0.0
Income                  7.8
Credit_Score            0.4
Credit_Utilization      0.0
Missed_Payments         0.0
Delinquent_Account      0.0
Loan_Balance            5.8
Debt_to_Income_Ratio    0.0
Employment_Status       0.0
Account_Tenure          0.0
Credit_Card_Type        0.0
Location                0.0
Month_1                 0.0
Month_2                 0.0
Month_3                 0.0
Month_4                 0.0
Month_5                 0.0
Month_6                 0.0
dtype: float64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
for col in df.select_dtypes(include='object').columns:
    print(col, df[col].unique())

Customer_ID ['CUST0001' 'CUST0002' 'CUST0003' 'CUST0004' 'CUST0005' 'CUST0006'
 'CUST0007' 'CUST0008' 'CUST0009' 'CUST0010' 'CUST0011' 'CUST0012'
 'CUST0013' 'CUST0014' 'CUST0015' 'CUST0016' 'CUST0017' 'CUST0018'
 'CUST0019' 'CUST0020' 'CUST0021' 'CUST0022' 'CUST0023' 'CUST0024'
 'CUST0025' 'CUST0026' 'CUST0027' 'CUST0028' 'CUST0029' 'CUST0030'
 'CUST0031' 'CUST0032' 'CUST0033' 'CUST0034' 'CUST0035' 'CUST0036'
 'CUST0037' 'CUST0038' 'CUST0039' 'CUST0040' 'CUST0041' 'CUST0042'
 'CUST0043' 'CUST0044' 'CUST0045' 'CUST0046' 'CUST0047' 'CUST0048'
 'CUST0049' 'CUST0050' 'CUST0051' 'CUST0052' 'CUST0053' 'CUST0054'
 'CUST0055' 'CUST0056' 'CUST0057' 'CUST0058' 'CUST0059' 'CUST0060'
 'CUST0061' 'CUST0062' 'CUST0063' 'CUST0064' 'CUST0065' 'CUST0066'
 'CUST0067' 'CUST0068' 'CUST0069' 'CUST0070' 'CUST0071' 'CUST0072'
 'CUST0073' 'CUST0074' 'CUST0075' 'CUST0076' 'CUST0077' 'CUST0078'
 'CUST0079' 'CUST0080' 'CUST0081' 'CUST0082' 'CUST0083' 'CUST0084'
 'CUST0085' 'CUST0086' 'CUST0087' 'CUST0088' 'CUST0089' 'CUST0090'
 'CUST0091' 'CUST0092' 'CUST0093' 'CUST0094' 'CUST0095' 'CUST0096'
 'CUST0097' 'CUST0098' 'CUST0099' 'CUST0100' 'CUST0101' 'CUST0102'
 'CUST0103' 'CUST0104' 'CUST0105' 'CUST0106' 'CUST0107' 'CUST0108'
 'CUST0109' 'CUST0110' 'CUST0111' 'CUST0112' 'CUST0113' 'CUST0114'
 'CUST0115' 'CUST0116' 'CUST0117' 'CUST0118' 'CUST0119' 'CUST0120'
 'CUST0121' 'CUST0122' 'CUST0123' 'CUST0124' 'CUST0125' 'CUST0126'
 'CUST0127' 'CUST0128' 'CUST0129' 'CUST0130' 'CUST0131' 'CUST0132'
 'CUST0133' 'CUST0134' 'CUST0135' 'CUST0136' 'CUST0137' 'CUST0138'
 'CUST0139' 'CUST0140' 'CUST0141' 'CUST0142' 'CUST0143' 'CUST0144'
 'CUST0145' 'CUST0146' 'CUST0147' 'CUST0148' 'CUST0149' 'CUST0150'
 'CUST0151' 'CUST0152' 'CUST0153' 'CUST0154' 'CUST0155' 'CUST0156'
 'CUST0157' 'CUST0158' 'CUST0159' 'CUST0160' 'CUST0161' 'CUST0162'
 'CUST0163' 'CUST0164' 'CUST0165' 'CUST0166' 'CUST0167' 'CUST0168'
 'CUST0169' 'CUST0170' 'CUST0171' 'CUST0172' 'CUST0173' 'CUST0174'
 'CUST0175' 'CUST0176' 'CUST0177' 'CUST0178' 'CUST0179' 'CUST0180'
 'CUST0181' 'CUST0182' 'CUST0183' 'CUST0184' 'CUST0185' 'CUST0186'
 'CUST0187' 'CUST0188' 'CUST0189' 'CUST0190' 'CUST0191' 'CUST0192'
 'CUST0193' 'CUST0194' 'CUST0195' 'CUST0196' 'CUST0197' 'CUST0198'
 'CUST0199' 'CUST0200' 'CUST0201' 'CUST0202' 'CUST0203' 'CUST0204'
 'CUST0205' 'CUST0206' 'CUST0207' 'CUST0208' 'CUST0209' 'CUST0210'
 'CUST0211' 'CUST0212' 'CUST0213' 'CUST0214' 'CUST0215' 'CUST0216'
 'CUST0217' 'CUST0218' 'CUST0219' 'CUST0220' 'CUST0221' 'CUST0222'
 'CUST0223' 'CUST0224' 'CUST0225' 'CUST0226' 'CUST0227' 'CUST0228'
 'CUST0229' 'CUST0230' 'CUST0231' 'CUST0232' 'CUST0233' 'CUST0234'
 'CUST0235' 'CUST0236' 'CUST0237' 'CUST0238' 'CUST0239' 'CUST0240'
 'CUST0241' 'CUST0242' 'CUST0243' 'CUST0244' 'CUST0245' 'CUST0246'
 'CUST0247' 'CUST0248' 'CUST0249' 'CUST0250' 'CUST0251' 'CUST0252'
 'CUST0253' 'CUST0254' 'CUST0255' 'CUST0256' 'CUST0257' 'CUST0258'
 'CUST0259' 'CUST0260' 'CUST0261' 'CUST0262' 'CUST0263' 'CUST0264'
 'CUST0265' 'CUST0266' 'CUST0267' 'CUST0268' 'CUST0269' 'CUST0270'
 'CUST0271' 'CUST0272' 'CUST0273' 'CUST0274' 'CUST0275' 'CUST0276'
 'CUST0277' 'CUST0278' 'CUST0279' 'CUST0280' 'CUST0281' 'CUST0282'
 'CUST0283' 'CUST0284' 'CUST0285' 'CUST0286' 'CUST0287' 'CUST0288'
 'CUST0289' 'CUST0290' 'CUST0291' 'CUST0292' 'CUST0293' 'CUST0294'
 'CUST0295' 'CUST0296' 'CUST0297' 'CUST0298' 'CUST0299' 'CUST0300'
 'CUST0301' 'CUST0302' 'CUST0303' 'CUST0304' 'CUST0305' 'CUST0306'
 'CUST0307' 'CUST0308' 'CUST0309' 'CUST0310' 'CUST0311' 'CUST0312'
 'CUST0313' 'CUST0314' 'CUST0315' 'CUST0316' 'CUST0317' 'CUST0318'
 'CUST0319' 'CUST0320' 'CUST0321' 'CUST0322' 'CUST0323' 'CUST0324'
 'CUST0325' 'CUST0326' 'CUST0327' 'CUST0328' 'CUST0329' 'CUST0330'
 'CUST0331' 'CUST0332' 'CUST0333' 'CUST0334' 'CUST0335' 'CUST0336'
 'CUST0337' 'CUST0338' 'CUST0339' 'CUST0340' 'CUST0341' 'CUST0342'
 'CUST0343' 'CUST0344' 'CUST0345' 'CUST0346' 'CUST0347' 'CUST0348'
 'CUST0349' 'CUST0350' 'CUST0351' 'CUST0352' 'CUST0353' 'CUST0354'
 'CUST0355' 'CUST0356' 'CUST0357' 'CUST0358' 'CUST0359' 'CUST0360'
 'CUST0361' 'CUST0362' 'CUST0363' 'CUST0364' 'CUST0365' 'CUST0366'
 'CUST0367' 'CUST0368' 'CUST0369' 'CUST0370' 'CUST0371' 'CUST0372'
 'CUST0373' 'CUST0374' 'CUST0375' 'CUST0376' 'CUST0377' 'CUST0378'
 'CUST0379' 'CUST0380' 'CUST0381' 'CUST0382' 'CUST0383' 'CUST0384'
 'CUST0385' 'CUST0386' 'CUST0387' 'CUST0388' 'CUST0389' 'CUST0390'
 'CUST0391' 'CUST0392' 'CUST0393' 'CUST0394' 'CUST0395' 'CUST0396'
 'CUST0397' 'CUST0398' 'CUST0399' 'CUST0400' 'CUST0401' 'CUST0402'
 'CUST0403' 'CUST0404' 'CUST0405' 'CUST0406' 'CUST0407' 'CUST0408'
 'CUST0409' 'CUST0410' 'CUST0411' 'CUST0412' 'CUST0413' 'CUST0414'
 'CUST0415' 'CUST0416' 'CUST0417' 'CUST0418' 'CUST0419' 'CUST0420'
 'CUST0421' 'CUST0422' 'CUST0423' 'CUST0424' 'CUST0425' 'CUST0426'
 'CUST0427' 'CUST0428' 'CUST0429' 'CUST0430' 'CUST0431' 'CUST0432'
 'CUST0433' 'CUST0434' 'CUST0435' 'CUST0436' 'CUST0437' 'CUST0438'
 'CUST0439' 'CUST0440' 'CUST0441' 'CUST0442' 'CUST0443' 'CUST0444'
 'CUST0445' 'CUST0446' 'CUST0447' 'CUST0448' 'CUST0449' 'CUST0450'
 'CUST0451' 'CUST0452' 'CUST0453' 'CUST0454' 'CUST0455' 'CUST0456'
 'CUST0457' 'CUST0458' 'CUST0459' 'CUST0460' 'CUST0461' 'CUST0462'
 'CUST0463' 'CUST0464' 'CUST0465' 'CUST0466' 'CUST0467' 'CUST0468'
 'CUST0469' 'CUST0470' 'CUST0471' 'CUST0472' 'CUST0473' 'CUST0474'
 'CUST0475' 'CUST0476' 'CUST0477' 'CUST0478' 'CUST0479' 'CUST0480'
 'CUST0481' 'CUST0482' 'CUST0483' 'CUST0484' 'CUST0485' 'CUST0486'
 'CUST0487' 'CUST0488' 'CUST0489' 'CUST0490' 'CUST0491' 'CUST0492'
 'CUST0493' 'CUST0494' 'CUST0495' 'CUST0496' 'CUST0497' 'CUST0498'
 'CUST0499' 'CUST0500']
Employment_Status ['EMP' 'Self-employed' 'Unemployed' 'employed' 'Employed' 'retired']
Credit_Card_Type ['Student' 'Standard' 'Platinum' 'Gold' 'Business']
Location ['Los Angeles' 'Phoenix' 'Chicago' 'New York' 'Houston']
Month_1 ['Late' 'Missed' 'On-time']
Month_2 ['Late' 'Missed' 'On-time']
Month_3 ['Missed' 'Late' 'On-time']
Month_4 ['Late' 'Missed' 'On-time']
Month_5 ['Missed' 'On-time' 'Late']
Month_6 ['Late' 'On-time' 'Missed']

In [15]:
df.describe()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Account_Tenure
count,500.000000,461.000000,498.000000,500.000000,500.000000,500.000000,471.000000,500.000000,500.000000
mean,46.266000,108379.893709,577.716867,0.491446,2.968000,0.160000,48654.428875,0.298862,9.740000
std,16.187629,53662.723741,168.881211,0.197103,1.946935,0.366973,29395.537273,0.094521,5.923054
min,18.000000,15404.000000,301.000000,0.050000,0.000000,0.000000,612.000000,0.100000,0.000000
25%,33.000000,62295.000000,418.250000,0.356486,1.000000,0.000000,23716.500000,0.233639,5.000000
50%,46.500000,107658.000000,586.000000,0.485636,3.000000,0.000000,45776.000000,0.301634,10.000000
75%,59.250000,155734.000000,727.250000,0.634440,5.000000,0.000000,75546.500000,0.362737,15.000000
max,74.000000,199943.000000,847.000000,1.025843,6.000000,1.000000,99620.000000,0.552956,19.000000

In [16]:
df.head()

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6
0,CUST0001,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,EMP,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late
1,CUST0002,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time
2,CUST0003,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late
3,CUST0004,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late
4,CUST0005,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late

In [17]:
df_clean = df.copy()

In [18]:
num_cols = df_clean.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    df_clean[col].fillna(df_clean[col].median(), inplace=True)

/tmp/ipykernel_26343/2269590824.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean[col].fillna(df_clean[col].median(), inplace=True)

In [19]:
cat_cols = df_clean.select_dtypes(include='object').columns

for col in cat_cols:
    df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

/tmp/ipykernel_26343/3034606905.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

In [20]:
df_clean.drop_duplicates(inplace=True)

In [21]:
for col in cat_cols:
    df_clean[col] = df_clean[col].str.strip().str.lower()

In [ ]:
df_clean.columns

Index(['Customer_ID', 'Age', 'Income', 'Credit_Score', 'Credit_Utilization',
       'Missed_Payments', 'Delinquent_Account', 'Loan_Balance',
       'Debt_to_Income_Ratio', 'Employment_Status', 'Account_Tenure',
       'Credit_Card_Type', 'Location', 'Month_1', 'Month_2', 'Month_3',
       'Month_4', 'Month_5', 'Month_6'],
      dtype='object')

In [24]:
df_clean.dtypes

Customer_ID              object
Age                       int64
Income                  float64
Credit_Score            float64
Credit_Utilization      float64
Missed_Payments           int64
Delinquent_Account        int64
Loan_Balance            float64
Debt_to_Income_Ratio    float64
Employment_Status        object
Account_Tenure            int64
Credit_Card_Type         object
Location                 object
Month_1                  object
Month_2                  object
Month_3                  object
Month_4                  object
Month_5                  object
Month_6                  object
dtype: object

In [25]:
df_clean['Age_Group'] = pd.cut(
    df_clean['Age'],
    bins=[0, 25, 35, 50, 65, 120],
    labels=['Young', 'Early Career', 'Mid Career', 'Senior', 'Retired']
)

In [26]:
df_clean.info()
df_clean.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           500 non-null    object
 1   Age                   500 non-null    int64
 2   Income                500 non-null    float64
 3   Credit_Score          500 non-null    float64
 4   Credit_Utilization    500 non-null    float64
 5   Missed_Payments       500 non-null    int64
 6   Delinquent_Account    500 non-null    int64
 7   Loan_Balance          500 non-null    float64
 8   Debt_to_Income_Ratio  500 non-null    float64
 9   Employment_Status     500 non-null    object
 10  Account_Tenure        500 non-null    int64
 11  Credit_Card_Type      500 non-null    object
 12  Location              500 non-null    object
 13  Month_1               500 non-null    object
 14  Month_2               500 non-null    object
 15  Month_3               500 non-null    object
 16  Month_4               500 non-null    object
 17  Month_5               500 non-null    object
 18  Month_6               500 non-null    object
 19  Age_Group             500 non-null    category
dtypes: category(1), float64(5), int64(4), object(10)
memory usage: 75.0+ KB

Customer_ID             0
Age                     0
Income                  0
Credit_Score            0
Credit_Utilization      0
Missed_Payments         0
Delinquent_Account      0
Loan_Balance            0
Debt_to_Income_Ratio    0
Employment_Status       0
Account_Tenure          0
Credit_Card_Type        0
Location                0
Month_1                 0
Month_2                 0
Month_3                 0
Month_4                 0
Month_5                 0
Month_6                 0
Age_Group               0
dtype: int64

In [27]:
df_clean.to_csv('../data/cleaned/cleaned_customer_credit_data.csv', index=False)